// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reward_Flow_v2.Rewards.Data.Database;

#nullable disable

namespace RewardFlow_API.Migrations.RewardDb
{
    [DbContext(typeof(RewardDbContext))]
    [Migration("20251224193531_InitialCreate_RewardDb")]
    partial class InitialCreate_RewardDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.EmployeeReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsUpdated")
                        .HasColumnType("bit");

                    b.Property<int?>("RewardEntityId")
                        .HasColumnType("int");

                    b.Property<int>("RewardId")
                        .HasColumnType("int")
                        .HasColumnName("reward_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("RewardEntityId");

                    b.ToTable("employee_rewards", "dbo");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.EmployeeSessionRewardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("NumberOfSessions")
                        .HasColumnType("int");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.Property<int>("SubjectSessionRewardId")
                        .HasColumnType("int")
                        .HasColumnName("subject_session_reward_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectSessionRewardId");

                    b.ToTable("employee_session_rewards", "dbo");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.RewardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("int")
                        .HasColumnName("number_of_employees");

                    b.Property<int>("RewardType")
                        .HasColumnType("int")
                        .HasColumnName("reward_type");

                    b.Property<decimal>("Total")
                        .HasColumnType("smallmoney")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("rewards", "dbo");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.SemesterSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumberOfStudents")
                        .HasColumnType("int")
                        .HasColumnName("number_of_students");

                    b.Property<float?>("Price")
                        .HasColumnType("real");

                    b.Property<byte>("SemesterNumber")
                        .HasColumnType("tinyint")
                        .HasColumnName("semester_number");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("subject_semesters", "dbo");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.SessionRewardEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("session_reward_id");

                    b.Property<float>("Percentage")
                        .HasColumnType("real")
                        .HasColumnName("percentage");

                    b.Property<byte?>("semester")
                        .HasColumnType("tinyint")
                        .HasColumnName("Semester");

                    b.Property<int?>("year")
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("session_rewards", "dbo");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPractical")
                        .HasColumnType("bit")
                        .HasColumnName("is_practical");

                    b.Property<bool>("IsTheoretical")
                        .HasColumnType("bit")
                        .HasColumnName("is_theoretical");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("SubjectPrice")
                        .HasColumnType("smallmoney")
                        .HasColumnName("subject_price");

                    b.HasKey("Id");

                    b.ToTable("subjects", "dbo");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.SubjectSessionRewardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MainEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("main_employee_id");

                    b.Property<int>("MaxNumberOfEmployees")
                        .HasColumnType("int")
                        .HasColumnName("max_number_of_employees");

                    b.Property<int>("NumberOfSessions")
                        .HasColumnType("int")
                        .HasColumnName("number_of_sessions");

                    b.Property<int>("SemesterSubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int>("SessionRewardId")
                        .HasColumnType("int")
                        .HasColumnName("session_reward_id");

                    b.Property<int>("StudentsNumber")
                        .HasColumnType("int")
                        .HasColumnName("students_number");

                    b.HasKey("Id");

                    b.HasIndex("SemesterSubjectId");

                    b.ToTable("subject_session_rewards", "dbo");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.EmployeeReward", b =>
                {
                    b.HasOne("Reward_Flow_v2.Rewards.Data.RewardEntity", null)
                        .WithMany("EmployeeRewards")
                        .HasForeignKey("RewardEntityId");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.EmployeeSessionRewardEntity", b =>
                {
                    b.HasOne("Reward_Flow_v2.Rewards.Data.SubjectSessionRewardEntity", "SubjectSessionReward")
                        .WithMany("Employees")
                        .HasForeignKey("SubjectSessionRewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjectSessionReward");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.SemesterSubject", b =>
                {
                    b.HasOne("Reward_Flow_v2.Rewards.Data.Subject", "Subject")
                        .WithMany("SubjectSemesters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.SessionRewardEntity", b =>
                {
                    b.HasOne("Reward_Flow_v2.Rewards.Data.RewardEntity", "Reward")
                        .WithOne()
                        .HasForeignKey("Reward_Flow_v2.Rewards.Data.SessionRewardEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.SubjectSessionRewardEntity", b =>
                {
                    b.HasOne("Reward_Flow_v2.Rewards.Data.SemesterSubject", null)
                        .WithMany()
                        .HasForeignKey("SemesterSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.RewardEntity", b =>
                {
                    b.Navigation("EmployeeRewards");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.Subject", b =>
                {
                    b.Navigation("SubjectSemesters");
                });

            modelBuilder.Entity("Reward_Flow_v2.Rewards.Data.SubjectSessionRewardEntity", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
