// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reward_Flow_v2.Employees.Data.Database;

#nullable disable

namespace Reward_Flow_v2.Migrations.EmployeeDb
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reward_Flow_v2.Employees.Data.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("faculty_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("DepartmentId");

                    b.HasIndex("FacultyId");

                    b.ToTable("departments", "dbo");
                });

            modelBuilder.Entity("Reward_Flow_v2.Employees.Data.Employees", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("account_number");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("faculty_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<byte?>("JobTitle")
                        .HasColumnType("tinyint")
                        .HasColumnName("job_title");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("national_number");

                    b.Property<float?>("Salary")
                        .HasColumnType("real")
                        .HasColumnName("salary");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("JobTitle");

                    b.HasIndex("Status");

                    b.ToTable("employees", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_Salary_NonNegative", "[salary] >= 0 OR [salary] IS NULL");
                        });
                });

            modelBuilder.Entity("Reward_Flow_v2.Employees.Data.EmployeeStatus", b =>
                {
                    b.Property<byte>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("StatusId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("StatusId");

                    b.ToTable("employee_status", "dbo");

                    b.HasData(
                        new
                        {
                            StatusId = (byte)1,
                            Description = "Active employee",
                            Name = "Active"
                        },
                        new
                        {
                            StatusId = (byte)2,
                            Description = "Inactive employee",
                            Name = "Inactive"
                        },
                        new
                        {
                            StatusId = (byte)3,
                            Description = "Suspended employee",
                            Name = "Suspended"
                        });
                });

            modelBuilder.Entity("Reward_Flow_v2.Employees.Data.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("faculty_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("FacultyId");

                    b.HasIndex(new[] { "CreatedBy", "Name" }, "UQ_Faculties_CreatedBy_Name")
                        .IsUnique();

                    b.ToTable("faculties", "dbo");
                });

            modelBuilder.Entity("Reward_Flow_v2.Employees.Data.JobTitle", b =>
                {
                    b.Property<byte>("JobTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("job_title_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("JobTitleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("JobTitleId");

                    b.HasIndex(new[] { "Name" }, "UQ__job_title__72E12F1B42005F0D")
                        .IsUnique();

                    b.ToTable("job_titles", "dbo");

                    b.HasData(
                        new
                        {
                            JobTitleId = (byte)1,
                            Description = "Regular employee",
                            Name = "Employees"
                        },
                        new
                        {
                            JobTitleId = (byte)2,
                            Description = "Professor",
                            Name = "Professor"
                        },
                        new
                        {
                            JobTitleId = (byte)3,
                            Description = "Teaching Assistant or Graduate Assistant",
                            Name = "Teaching Assistant / Graduate Assistant"
                        });
                });

            modelBuilder.Entity("Reward_Flow_v2.User.Data.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastEdit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plan", "dbo");
                });

            modelBuilder.Entity("Reward_Flow_v2.User.Data.User", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UUID");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("User", "dbo");
                });

            modelBuilder.Entity("Reward_Flow_v2.User.Data.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRole", "dbo");
                });

            modelBuilder.Entity("Reward_Flow_v2.Employees.Data.Department", b =>
                {
                    b.HasOne("Reward_Flow_v2.Employees.Data.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Reward_Flow_v2.Employees.Data.Employees", b =>
                {
                    b.HasOne("Reward_Flow_v2.User.Data.User", "CreatedByNavigation")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reward_Flow_v2.Employees.Data.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Reward_Flow_v2.Employees.Data.Faculty", "Faculty")
                        .WithMany("Employees")
                        .HasForeignKey("FacultyId");

                    b.HasOne("Reward_Flow_v2.Employees.Data.JobTitle", "JobTitleNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("JobTitle");

                    b.HasOne("Reward_Flow_v2.Employees.Data.EmployeeStatus", "StatusNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("Status");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Department");

                    b.Navigation("Faculty");

                    b.Navigation("JobTitleNavigation");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("Reward_Flow_v2.Employees.Data.Faculty", b =>
                {
                    b.HasOne("Reward_Flow_v2.User.Data.User", "CreatedByNavigation")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("Reward_Flow_v2.User.Data.User", b =>
                {
                    b.HasOne("Reward_Flow_v2.User.Data.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reward_Flow_v2.User.Data.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId");

                    b.Navigation("Plan");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Reward_Flow_v2.Employees.Data.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Reward_Flow_v2.Employees.Data.EmployeeStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Reward_Flow_v2.Employees.Data.Faculty", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Reward_Flow_v2.Employees.Data.JobTitle", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
